#!/usr/bin/env bash
set -e

cp /etc/hosts /etc/hosts.new
sed -i 's/::1\tlocalhost ip6-localhost ip6-loopback/::1 ip6-localhost ip6-loopback/' /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts

USER_ID=$(stat -c %u /workspace)
echo "Creating ubuntu user with UID : $USER_ID"
id -u ubuntu &> /dev/null || useradd --shell /bin/bash -u $USER_ID -o -c "" -m ubuntu
cp /stack/bash_aliases /home/ubuntu/.bash_aliases

exec "$@"
